/**
 * COGNIFY — Your Timetable (Day 4)
 * Generated from the adaptive loop: weak topics, retention, balance, goals.
 * Students can complete, skip or reschedule sessions; actions are logged
 * (mock) and feed the path ahead.
 *
 * Style: Scholar's Atelier — ledger, marginalia, mono stats, hairline rules.
 */
import AppShell, { PageHeader } from "@/components/cognify/AppShell";
import {
  ActionChip,
  Marginalia,
  StatCell,
} from "@/components/cognify/Primitives";
import { Button } from "@/components/ui/button";
import {
  timetableSessions,
  sessionsByPeriod,
  todaySessionCount,
  completeSession,
  skipSession,
  rescheduleSession,
  startSession,
} from "@/lib/timetable";
import { topicAlias } from "@/lib/curriculum";
import { Check, RotateCw, SkipForward, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const slugOf = (id: string) => topicAlias(id) ?? id;

const subjectNames: Record<string, string> = {
  MATH: "Mathematics",
  SCI: "Science",
  SST: "Social Science",
  ENG: "English",
  HIN: "Hindi",
  SKT: "Sanskrit",
};

type Status =
  | "scheduled"
  | "in-progress"
  | "completed"
  | "skipped"
  | "rescheduled";

export default function TimetablePage() {
  const seed = timetableSessions();
  const [statusMap, setStatusMap] = useState<Record<string, Status>>({});
  const periods = useMemo(() => ["today", "week", "upcoming"] as const, []);
  const sessions = seed.map((s) => ({
    ...s,
    status: (statusMap[s.id] ?? s.status) as Status,
  }));

  const completed = Object.values(statusMap).filter((s) => s === "completed").length;
  const skipped = Object.values(statusMap).filter((s) => s === "skipped").length;
  const todayTotal = todaySessionCount();
  const todayMinutes = sessions
    .filter((s) => s.period === "today" && s.status === "scheduled")
    .reduce((n, s) => n + s.durationMinutes, 0);

  function handleStart(id: string) {
    startSession(id);
    setStatusMap((m) => ({ ...m, [id]: "in-progress" }));
    toast.info("Session started", { description: "Interactions in the topic are logged for analytics." });
  }
  function handleComplete(id: string) {
    startSession(id);
    completeSession(id);
    setStatusMap((m) => ({ ...m, [id]: "completed" }));
    toast.success("Session marked complete", {
      description: "Logged to your Learning DNA — progress and evidence updated.",
    });
  }
  function handleSkip(id: string) {
    skipSession(id);
    setStatusMap((m) => ({ ...m, [id]: "skipped" }));
    toast.warning("Session skipped", {
      description: "The engine will re-balance today's plan. Consider logging why.",
    });
  }
  function handleReschedule(id: string) {
    rescheduleSession(id, "tomorrow");
    setStatusMap((m) => ({ ...m, [id]: "rescheduled" }));
    toast.info("Session rescheduled", { description: "Moved to tomorrow — the scheduler has been updated." });
  }

  return (
    <AppShell>
      <PageHeader
        overline="Your Timetable"
        title="Today, generated by the loop"
        subtitle="This timetable is not a static grid. It is regenerated from your adaptive path — weak topics first, retention windows second, subject balance third. You can complete, skip or reschedule; each choice feeds the engine."
      />

      <div className="px-5 py-7 sm:px-8 lg:px-10">
        {/* Stats ledger */}
        <div className="rise-in grid grid-cols-2 gap-y-6 border-b border-ink/10 pb-7 sm:grid-cols-4">
          <StatCell
            label="Sessions today"
            value={`${todayTotal}`}
            sub={`${todayMinutes} min scheduled`}
          />
          <StatCell
            label="Completed"
            value={`${completed}`}
            sub="logged to Learning DNA"
          />
          <StatCell
            label="Skipped"
            value={`${skipped}`}
            sub="plan will re-balance"
          />
            <StatCell
            label="Next up"
            value={
              sessions.find((s) => s.period === "today" && s.status === "scheduled")?.startTime ?? "—"
            }
            sub="auto-generated block"
          />
        </div>

        <div className="mt-10 space-y-12">
          {periods.map((p) => {
            const rows = sessions.filter((s) => s.period === p);
            return (
              <section key={p}>
                <div className="flex flex-wrap items-baseline justify-between gap-3">
                  <Marginalia amber={p === "today"}>
                    {p === "today" ? "Today — your adaptive plan" : p === "week" ? "This week — generated in advance" : "Upcoming — provisional blocks"}
                  </Marginalia>
                  <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                    {rows.length} {rows.length === 1 ? "session" : "sessions"}
                  </span>
                </div>
                <div className="mt-5 divide-y divide-ink/10 border-y border-ink/10">
                  {rows.map((s, i) => {
                    const isLive = s.period === "today";
                    const done = s.status === "completed";
                    const off = s.status === "skipped" || s.status === "rescheduled";
                    return (
                      <div
                        key={s.id}
                        className={
                          "rise-in grid gap-4 py-6 sm:grid-cols-[2.5rem_1fr]" +
                          (off ? " opacity-50" : "")
                        }
                      >
                        <div className="index-num pt-0.5">{String(i + 1).padStart(2, "0")}</div>
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="font-mono text-[10px] font-medium uppercase tracking-wider text-ink/50">
                              {subjectNames[s.subjectCode] ?? s.subjectCode}
                            </span>
                            <ActionChip action={s.activityType} />
                            {s.priority === "high" && (
                              <span className="font-mono text-[9px] font-bold uppercase tracking-[0.14em] text-amber-dark">
                                ● High impact
                              </span>
                            )}
                            {done && (
                              <span className="inline-flex items-center gap-1 font-mono text-[9px] font-medium uppercase tracking-wider text-teal-dark">
                                <Check className="h-3 w-3" /> Completed
                              </span>
                            )}
                            {s.status === "skipped" && (
                              <span className="inline-flex items-center gap-1 font-mono text-[9px] font-medium uppercase tracking-wider text-muted-foreground">
                                <SkipForward className="h-3 w-3" /> Skipped
                              </span>
                            )}
                            {s.status === "rescheduled" && (
                              <span className="inline-flex items-center gap-1 font-mono text-[9px] font-medium uppercase tracking-wider text-amber-dark">
                                <RotateCw className="h-3 w-3" /> Rescheduled to tomorrow
                              </span>
                            )}
                          </div>
                          <h3 className="mt-1.5 font-serif text-xl font-bold text-ink">{s.topicTitle}</h3>
                          <div className="mt-2.5 flex items-start gap-2">
                            <span className="mt-1 shrink-0 font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-teal">
                              Why this block
                            </span>
                            <p className="footnote">{s.reason}</p>
                          </div>
                          <div className="mt-4 flex flex-wrap items-center gap-4">
                            <span className="font-mono text-[11px] text-dark-text/60">
                              {isLive ? `${s.startTime}–${s.endTime}` : "auto-scheduled"} ·{" "}
                              {s.durationMinutes} min
                            </span>
                            {isLive && !done && s.status === "scheduled" && (
                              <div className="flex flex-wrap items-center gap-2">
                                <Button
                                  size="sm"
                                  className="h-8 border border-teal bg-teal px-3 text-[11px] uppercase tracking-wider text-ivory hover:bg-teal/90"
                                  onClick={() => handleStart(s.id)}
                                >
                                  Begin
                                </Button>
                                <Button
                                  size="sm"
                                  className="h-8 border border-ink bg-ink px-3 text-[11px] uppercase tracking-wider text-ivory hover:bg-ink/90"
                                  onClick={() => handleComplete(s.id)}
                                >
                                  <Check className="mr-1 h-3.5 w-3.5" /> Mark complete
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-8 border-ink/25 bg-transparent px-3 text-[11px] uppercase tracking-wider text-ink/80 hover:bg-ink/5"
                                  onClick={() => handleReschedule(s.id)}
                                >
                                  <RotateCw className="mr-1 h-3.5 w-3.5" /> Reschedule
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-8 border-ink/15 bg-transparent px-3 text-[11px] uppercase tracking-wider text-ink/50 hover:bg-ink/5"
                                  onClick={() => handleSkip(s.id)}
                                >
                                  <X className="mr-1 h-3.5 w-3.5" /> Skip
                                </Button>
                              </div>
                            )}
                            {s.status === "in-progress" && (
                              <Button
                                size="sm"
                                className="h-8 border border-ink bg-ink px-3 text-[11px] uppercase tracking-wider text-ivory hover:bg-ink/90"
                                onClick={() => handleComplete(s.id)}
                              >
                                <Check className="mr-1 h-3.5 w-3.5" /> Mark complete
                              </Button>
                            )}
                            {(s.status === "in-progress" || done) && (
                              <Link
                                href={`/topic/${slugOf(s.topicId)}`}
                                className="border-b border-teal/50 pb-0.5 font-mono text-[11px] uppercase tracking-wider text-teal transition-colors hover:border-teal"
                              >
                                Continue learning
                              </Link>
                            )}
                            {s.status === "rescheduled" && (
                              <span className="font-mono text-[10px] text-amber-dark">
                                moved to {s.rescheduledTo ?? "tomorrow"}
                              </span>
                            )}
                            {isLive && (
                              <Link
                                href={`/topic/${slugOf(s.topicId)}`}
                                className="border-b border-teal/50 pb-0.5 font-mono text-[11px] uppercase tracking-wider text-teal transition-colors hover:border-teal"
                              >
                                Open topic
                              </Link>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                  {rows.length === 0 && (
                    <p className="py-6 footnote">Nothing scheduled in this period yet.</p>
                  )}
                </div>
              </section>
            );
          })}
        </div>
      </div>
    </AppShell>
  );
}
